### ISSUE TITLE
protrac parameters

### ISSUE THREAD

**Issue by adriludwig** [kerogens101/Dmel_piCs#1]
Hi!
I’m currently using Protrac and working to understand the best parameters. I noticed that the parameters mentioned in the supplementary material of your paper differ from those in the GitHub code.

Would you mind clarifying which parameters you used in your work?
Also, what normalization do you mean when you say "normalized multi-mapped piRNA coverage of 25 or less"?

Thank you very much for your time and assistance.

**Comment by kerogens101** [comment]
Hi adriludwig, 

Thanks for letting me know! Parameters in the paper are the correct ones (also listed below). I mistakenly attached the script for calling piCs in a different species in github. 
-swsize 500 -swincr 100 -clsize 500 -1Tor10A 0.6 -pimin 23 -clhitsn 10 -pdens 0.2 -pti 

As for the piRNA coverage used to filter out proTRAC calls, was from the "Hits (normalized):" values in the results file from the proTRAC runs, which is essentially RPM values. I'll update the proTRAC script here in next few days.

**Comment by adriludwig** [comment]
Thanks very much for your reply!
